version: '3.9'

services:

  db:
    image: postgres:16.0-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: msd
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      MSDSETTINGS_DATABASES: '{"default":{"HOST":"db"}}'
      MSDSETTINGS_LOCAL_SETTINGS_PATH: 'local/settings.prod.py'

volumes:
  postgresql-data:
    driver: local
