EMAIL_BACKEND = 'django_ses.SESBackend'
DEFAULT_FROM_EMAIL = ''

AWS_SES_ACCESS_KEY_ID = ''
AWS_SES_SECRET_ACCESS_KEY = ''
AWS_SES_REGION_NAME = ''
AWS_SES_REGION_ENDPOINT = ''
AWS_SES_FROM_EMAIL = ''
USE_SES_V2 = True

DOMAIN = ''
SITE_NAME = ''
